---
- name: configuration
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: enable repos
    template:
      src: /open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: install httpie and Haproxy
    yum:
      name: 
      - httpie
      - haproxy
      state: present


  - name: enable HAProxy
    service:
      name: haproxy
      state: started
  
  - name: configure haproxy
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  
  - name: restart HAproxy
    service:
      name: haproxy
      state: restarted


- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true

  tasks:
  - name: install tomcat
    yum:
      name: tomcat
      state: present

  - name: enable tomcat at boot
    service:
      name: tomcat
      enabled: yes

  - name: create ansible tomcat directory
    file:
      path: /usr/share/tomcat/webapps/ROOT
      state: directory

  - name: copy static index.html to tomcat webapps/ansible/index.html
    template:
      src: index.html.j2
      dest: /usr/share/tomcat/webapps/ROOT/index.html
      mode: 0644

  - name: start tomcat
    service:
      name: tomcat
      state: started

- name: index.html on app 1 and 2
  hosts: 
  - app1
  - app2
  gather_facts: false
  become: true

  tasks:
  - name: copy static index.html to tomcat webapps/ansible/index.html
    template:
      src: index.html.app1
      dest: /usr/share/tomcat/webapps/ansible/index.html


- name: deploy postgres
  hosts: appsdbs
  gather_facts: false
  become: true

  tasks:
  - name: install progress
    yum:
      name: postresql-server
      state: present

  - name: enable apache at boot
    service:
      name: postgresql
      enabled: yes
  
  - name: initialize postgress by command
    command: postgresql-setup initdb

  - name: check config postgres
    command: chkconfig postgresql on

  - name: start postgres
    service:
      name: postgresql.service
      state: started

- name: deploy apache
  hosts: apps
  gather_facts: false
  become: true
    
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: present
  
  - name: enable apache at boot
    service:
      name: httpd
      enabled: yes

  - name: start apache
    service:
      name: httpd
      state: started
